export const imgSrc = [
  [
    { alt: "img-1.0", src: "src/assets/img/Story/img-1.jpg" },
    { alt: "img-2.0", src: "src/assets/img/Story/img-2.jpg" },
    { alt: "img-3.0", src: "src/assets/img/Story/img-3.jpg" },
    { alt: "img-4.0", src: "src/assets/img/Story/img-4.jpg" },
    { alt: "img-5.0", src: "src/assets/img/Story/img-5.jpg" },
  ],
  [
    { alt: "img-1.1", src: "src/assets/img/Story/img-6.jpg" },
    { alt: "img-2.1", src: "src/assets/img/Story/img-7.jpg" },
    { alt: "img-3.1", src: "src/assets/img/Story/img-8.jpg" },
    { alt: "img-4.1", src: "src/assets/img/Story/img-9.jpg" },
    { alt: "img-5.1", src: "src/assets/img/Story/img-10.jpg" },
  ],
  [
    { alt: "img-1.2", src: "src/assets/img/Story/img-11.jpg" },
    { alt: "img-2.2", src: "src/assets/img/Story/img-12.jpg" },
    { alt: "img-3.2", src: "src/assets/img/Story/img-13.jpg" },
    { alt: "img-4.2", src: "src/assets/img/Story/img-14.jpg" },
    { alt: "img-5.2", src: "src/assets/img/Story/img-15.jpg" },
  ],
  [
    { alt: "img-1.3", src: "src/assets/img/Story/img-16.jpg" },
    { alt: "img-2.3", src: "src/assets/img/Story/img-17.jpg" },
    { alt: "img-3.3", src: "src/assets/img/Story/img-18.jpg" },
    { alt: "img-4.3", src: "src/assets/img/Story/img-19.jpg" },
    { alt: "img-5.3", src: "src/assets/img/Story/img-20.jpg" },
  ],
  [
    { alt: "img-1.4", src: "src/assets/img/Story/img-21.jpg" },
    { alt: "img-2.4", src: "src/assets/img/Story/img-22.jpg" },
    { alt: "img-3.4", src: "src/assets/img/Story/img-23.jpg" },
    { alt: "img-4.4", src: "src/assets/img/Story/img-24.jpg" },
    { alt: "img-5.4", src: "src/assets/img/Story/img-25.jpg" },
  ],
  [
    { alt: "img-1.5", src: "src/assets/img/Story/img-26.jpg" },
    { alt: "img-2.5", src: "src/assets/img/Story/img-27.jpg" },
    { alt: "img-3.5", src: "src/assets/img/Story/img-28.jpg" },
    { alt: "img-4.5", src: "src/assets/img/Story/img-29.jpg" },
    { alt: "img-5.5", src: "src/assets/img/Story/img-30.jpg" },
  ],
  [
    { alt: "img-1.6", src: "src/assets/img/Story/img-31.jpg" },
    { alt: "img-2.6", src: "src/assets/img/Story/img-32.jpg" },
    { alt: "img-3.6", src: "src/assets/img/Story/img-33.jpg" },
    { alt: "img-4.6", src: "src/assets/img/Story/img-34.jpg" },
    { alt: "img-5.6", src: "src/assets/img/Story/img-35.jpg" },
  ],
  [
    { alt: "img-1.7", src: "src/assets/img/Story/img-36.jpg" },
    { alt: "img-2.7", src: "src/assets/img/Story/img-37.jpg" },
    { alt: "img-3.7", src: "src/assets/img/Story/img-38.jpg" },
    { alt: "img-4.7", src: "src/assets/img/Story/img-39.jpg" },
    { alt: "img-5.7", src: "src/assets/img/Story/img-40.jpg" },
  ],
  [
    { alt: "img-1.8", src: "src/assets/img/Story/img-41.jpg" },
    { alt: "img-2.8", src: "src/assets/img/Story/img-42.jpg" },
    { alt: "img-3.8", src: "src/assets/img/Story/img-43.jpg" },
    { alt: "img-4.8", src: "src/assets/img/Story/img-44.jpg" },
    { alt: "img-5.8", src: "src/assets/img/Story/img-45.jpg" },
  ],
  [
    { alt: "img-1.9", src: "src/assets/img/Story/img-46.jpg" },
    { alt: "img-2.9", src: "src/assets/img/Story/img-47.jpg" },
    { alt: "img-3.9", src: "src/assets/img/Story/img-48.jpg" },
    { alt: "img-4.9", src: "src/assets/img/Story/img-49.jpg" },
    { alt: "img-5.9", src: "src/assets/img/Story/img-50.jpg" },
  ],
  [
    { alt: "img-1.10", src: "src/assets/img/Story/img-51.jpg" },
    { alt: "img-2.10", src: "src/assets/img/Story/img-52.jpg" },
    { alt: "img-3.10", src: "src/assets/img/Story/img-53.jpg" },
    { alt: "img-4.10", src: "src/assets/img/Story/img-54.jpg" },
    { alt: "img-5.10", src: "src/assets/img/Story/img-55.jpg" },
  ],
  [
    { alt: "img-1.11", src: "src/assets/img/Story/img-56.jpg" },
    { alt: "img-2.11", src: "src/assets/img/Story/img-57.jpg" },
    { alt: "img-3.11", src: "src/assets/img/Story/img-58.jpg" },
    { alt: "img-4.11", src: "src/assets/img/Story/img-59.jpg" },
    { alt: "img-5.11", src: "src/assets/img/Story/img-60.jpg" },
  ],
];
