export const CHARACTER_DATA = [
  {
    id: 0,
    mainImage: "src/assets/img/Character/contents_character_stand01.png",
    firstName: "篠原",
    secondName: "緋呂斗",
    fullName: "Shinohara Hiroto",
    cvName: "中村",
    comments: "源太",
    frstParagraph: "四番区英明学園所属。高校二年生。",
    scndParagraph: "等級 ：7ツ星",
    thrdParagraph: "学園島に編入してきたばかりの転校生 更紗を《決闘》で負かしてしまい、いきなり学園島 。最強の7ツ星（偽）になることに ある目的〟のために嘘を承知で頂点に君臨し続けることを決意する",
    secondImage: "src/assets/img/Character/contents_character_face01.png",
  },
  {
    id: 1,
    mainImage: "src/assets/img/Character/contents_character_stand02.png",
    firstName: "姫路",
    secondName: "白雪",
    fullName: "Himeji Shirayuki",
    cvName: "首藤",
    comments: "志奈",
    frstParagraph: "四番区英明学園所属。高校二年生。",
    scndParagraph: "等級 ：4ツ星",
    thrdParagraph: "完全無欠のイカサマチートメイド。緋呂斗の補佐をする《カンパニー》の長であり、彼の《決闘=》を〝必勝〟に 導くためイカサマ上等の戦術を指南する。メイドとしての世話も住み込みで実施中。",
    secondImage: "src/assets/img/Character/contents_character_face02.png",
  },
  {
    id: 2,
    mainImage: "src/assets/img/Character/contents_character_stand03.png",
    firstName: "彩園寺",
    secondName: "更紗",
    fullName: "Saionji Sarasa",
    cvName: "倉持",
    comments: "若菜",
    frstParagraph: "三番区桜花学園所属。高校二年生。",
    scndParagraph: "等級 ：6ツ星",
    thrdParagraph: "学園島を統べる彩園寺家の令嬢。入学早々に〝７ツ星〟となり、長い間《女帝》の呼び名で畏怖されていた実 力者だが、編入してきた緋呂斗に《決闘》で敗れ6ツ星に降格。",
    secondImage: "src/assets/img/Character/contents_character_face03.png",
  },
  {
    id: 3,
    mainImage: "src/assets/img/Character/contents_character02_stand01.png",
    firstName: "秋月",
    secondName: "乃愛",
    fullName: "Akizuki Noa",
    cvName: "立花",
    comments: "理香",
    frstParagraph: "四番区英明学園所属。高校三年生。",
    scndParagraph: "等級 ：6ツ星",
    thrdParagraph: "あざと可愛い見た目に反し悪辣非道な戦い方を得意とする通称《小悪魔》。進司や七瀬と同じ6ツ星プレイヤーだが、《決闘》での戦績は彼らを上回ると いう正真正銘のトップランカー。",
    secondImage: "src/assets/img/Character/contents_character02_face01.png",
  },
  {
    id: 4,
    mainImage: "src/assets/img/Character/contents_character02_stand02.png",
    firstName: "椎名",
    secondName: "紬",
    fullName: "Shiina Tsumugi",
    cvName: "森山",
    comments: "由梨佳",
    frstParagraph: "緋呂斗の前に突如現れた謎の中学生。",
    scndParagraph: "等級 ：6ツ星",
    thrdParagraph: "中二病と自尊心とを存分に拗らせているタイプの少女。自称《闇の一族》で あり、その右目は《魔眼》になっている（らしい）。基本的には人見知りだが、一緒にゲームで遊んでくれた",
    secondImage: "src/assets/img/Character/contents_character02_face02.png",
  },
  {
    id: 5,
    mainImage: "src/assets/img/Character/contents_character02_stand03.png",
    firstName: "一ノ瀬",
    secondName: "棗",
    fullName: "Ichinose Natsume",
    cvName: "桑島",
    comments: "法子",
    frstParagraph: "四番区英明学園の学長。",
    scndParagraph: "等級 ：6ツ星",
    thrdParagraph: "緋呂斗を学園島にスカウトしてきた人物であり、学園島最強の7ツ星という特 大の〝嘘〟をつき続けるきっかけとなった張本人。ドS 緋呂斗を利用することで成し遂げたい〝野望〟とは……。",
    secondImage: "src/assets/img/Character/contents_character02_face03.png",
  },
  {
    id: 6,
    mainImage: "src/assets/img/Character/contents_character02_stand04.png",
    firstName: "加賀谷",
    secondName: "亜未",
    fullName: "Kagaya Ami",
    cvName: "山村",
    comments: "響",
    frstParagraph: "白雪率いる《カンパニー》の電子機器担当。",
    scndParagraph: "等級 ：6ツ星",
    thrdParagraph: "見た目は絵に描いたようなダラダラ系お姉さん（美人）。ただしPCや端末関 係の扱いにはめっぽう強く、そのハッキングスキルは一級品。白雪と共に〝イカサマ〟を通して緋呂斗をサポートする。",
    secondImage: "src/assets/img/Character/contents_character02_face04.png",
  },
  {
    id: 7,
    mainImage: "src/assets/img/Character/contents_character02_stand05.png",
    firstName: "多々良",
    secondName: "楓花",
    fullName: "Tatar Fuuka",
    cvName: "瀬戸",
    comments: "桃子",
    frstParagraph: "四番区英明学園所属。高校二年生。",
    scndParagraph: "等級 ：3ツ星",
    thrdParagraph: "緋呂斗が在籍する2-Aのクラス委員長。素直で明るく、リアクションを取る度に自前のポニーテールが背中で跳ねる元気っ子。人に頼られるのが大好きな世話焼きタイプでもあり、",
    secondImage: "src/assets/img/Character/contents_character02_face05.png",
  },
  {
    id: 8,
    mainImage: "src/assets/img/Character/contents_character02_stand06.png",
    firstName: "辻",
    secondName: "友紀",
    fullName: "Tsuji Yuuki",
    cvName: "望月",
    comments: "麻衣",
    frstParagraph: "四番区英明学園所属。高校二年生。",
    scndParagraph: "等級 ：3ツ星",
    thrdParagraph: "楓花と同じく、緋呂斗が在籍する2-Aのクラスメイト。男物の制服を着ていなければ女子に見間違えられるくらい中性的な顔立ちを持つ美少年。先輩女子からの人気が非常に高い。",
    secondImage: "src/assets/img/Character/contents_character02_face06.png",
  },
  {
    id: 9,
    mainImage: "src/assets/img/Character/contents_character03_stand01.png",
    firstName: "久我崎",
    secondName: "晴嵐",
    fullName: "Kugasaki Seiran",
    cvName: "福山",
    comments: "潤",
    frstParagraph: "八番区音羽学園所属。高校三年生。",
    scndParagraph: "等級 ：5ツ星",
    thrdParagraph: "非公式治安維持組織《我流聖騎士団》のリーダー。通称〝不死鳥〟。その目立つ風貌と確かな実力から島内トップクラスの知名度を持つ。かつて自身を打ち負かした更紗を",
    secondImage: "src/assets/img/Character/contents_character03_face01.png",
  },
  {
    id: 10,
    mainImage: "src/assets/img/Character/contents_character03_stand02.png",
    firstName: "榎本",
    secondName: "進司",
    fullName: "Enomoto Shinji",
    cvName: "榎木",
    comments: "淳弥",
    frstParagraph: "四番区英明学園所属。高校三年生。",
    scndParagraph: "等級 ：6ツ星",
    thrdParagraph: "英明学園の現生徒会長であり、瞬間記憶能力を持つとすら囁かれる頭脳明晰な強豪プレイヤー。その実力から《千里眼》の異名を持つ。同じく6ツ星の七瀬とは腐れ縁の幼馴染みで、",
    secondImage: "src/assets/img/Character/contents_character03_face02.png",
  },
  {
    id: 11,
    mainImage: "src/assets/img/Character/contents_character03_stand03.png",
    firstName: "浅宮",
    secondName: "七瀬",
    fullName: "Asamiya Nanase",
    cvName: "大西",
    comments: "沙織",
    frstParagraph: "四番区英明学園所属。高校三年生。",
    scndParagraph: "等級 ：6ツ星",
    thrdParagraph: "幼馴染みの進司と並び、英明学園を代表する6ツ星プレイヤー。ファッション誌でモデルをしていた過去を持ち、当然ながらスタイルは抜 群。白雪を含め後輩女子から羨望の眼差しを集めている。",
    secondImage: "src/assets/img/Character/contents_character03_face03.png",
  },
  {
    id: 12,
    mainImage: "src/assets/img/Character/contents_character03_stand04.png",
    firstName: "風見",
    secondName: "鈴蘭",
    fullName: "Kazami Suzuran",
    cvName: "徳井",
    comments: "青空",
    frstParagraph: "三番区桜花学園所属。高校二年生。",
    scndParagraph: "等級 ：3ツ星",
    thrdParagraph: "学園島全土で読まれているネットニュースアプリ〝LNN〟を運営する学園島 公認組織《ライブラ》の主要メンバー。大規模《決闘》の司会や審判を務めることも多く、",
    secondImage: "src/assets/img/Character/contents_character03_face04.png",
  },
];
