export const profileImgData = [
  { src: "src/assets/img/Character/contents_character_icon01.png" },
  { src: "src/assets/img/Character/contents_character_icon02.png" },
  { src: "src/assets/img/Character/contents_character_icon03.png" },
  { src: "src/assets/img/Character/contents_character02_icon01.png" },
  { src: "src/assets/img/Character/contents_character02_icon02.png" },
  { src: "src/assets/img/Character/contents_character02_icon03.png" },
  { src: "src/assets/img/Character/contents_character02_icon04.png" },
  { src: "src/assets/img/Character/contents_character02_icon05.png" },
  { src: "src/assets/img/Character/contents_character02_icon06.png" },
  { src: "src/assets/img/Character/contents_character03_icon01.png" },
  { src: "src/assets/img/Character/contents_character03_icon02.png" },
  { src: "src/assets/img/Character/contents_character03_icon03.png" },
  { src: "src/assets/img/Character/contents_character03_icon04.png" },
];
